version: 2
container_config: &container_config
  working_directory: ~/personal-website
  docker:
    - image: node:11.10.1
jobs:
  install:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/personal-website
          paths: .
  test:
    <<: *container_config
    steps:
      - attach_workspace:
          at: ~/personal-website
      - run:
          name: Run Tests
          command: npm test
  build:
    <<: *container_config
    steps:
      - attach_workspace:
          at: ~/personal-website
      - run:
          name: Build React App
          command: npm run build
      - persist_to_workspace:
          root: ~/personal-website
          paths: .
  deploy:
    <<: *container_config
    steps:
      - attach_workspace:
          at: ~/personal-website
      - run:
          name: Push to Repository
          command: |
            chmod +x ./deploy.sh
            .deploy.sh

workflows:
  version: 2
  deploy_personal_website:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
      - deploy:
          context: PERSONAL_WEBSITE
          filters:
            branches:
              only:
                - master
          requires:
            - install
            - test
            - build